version: '3'

services:

  nginx:
    image: nginx:1.16.1-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./localhost.cert:/etc/ssl/localhost.cert
      - ./localhost.key:/etc/ssl/localhost.key
    links:
      - vtiger

  vtiger:
    image: javanile/vtiger:7.1.0
    environment:
      - VT_DEBUG=true
      - VT_SITE_URL=https://localhost/
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=vtiger
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - 8080:80
    volumes:
      - ./:/app
      - ./volume:/var/lib/vtiger
      - ./config_override.php:/var/www/html/config_override.php
    links:
      - mysql

  mysql:
    image: mysql:5.5
    environment:
      - MYSQL_DATABASE=vtiger
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - mysql:/var/lib/mysql:rw

  adminer:
    image: javanile/adminer
    environment:
      - MYSQL_DATABASE=vtiger
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - "8081:8080"

volumes:
  mysql:
