enum QueryKeys {
  LOGIN = 'LOGIN',
  SIGNUP = 'SIGNUP',
  GET_OTP = 'GET_OTP',
  VERIFY_NAMES = 'VERIFY_NAMES',
  GET_USER_DETAILS = 'GET_USER_DETAILS',
  VERIFY_JWT = 'VERIFY_JWT',
  GET_ALL_USERS = 'GET_ALL_USERS',
  INITIATE_TRANSACTION = 'INITIATE_TRANSACTION',
  GET_TRANSACTIONS = 'GET_TRANSACTIONS',
  VERIFY_BVN = 'VERIFY_BVN',
  GET_WALLET_BALANCE = 'GET_WALLET_BALANCE',
}

export default QueryKeys;
