enum QueryKeys {
  LOGIN = 'LOGIN',
  SIGNUP = 'SIGNUP',
  GET_OTP = 'GET_OTP',
  GET_USER_DETAILS = 'GET_USER_DETAILS',
  VERIFY_OTP = 'VERIFY_OTP',
  VERIFY_JWT = 'VERIFY_JWT',
  GET_ALL_USERS = 'GET_ALL_USERS',
  GET_ALL_MILEAGE = 'GET_ALL_MILEAGE',
  GET_ALL_BUSINESSES = 'GET_ALL_BUSINESSES',
  GET_TRANSACTIONS = 'GET_TRANSACTIONS',
  GET_USER_BY_ID = 'GET_USER_BY_ID',
  GET_MILEAGE_BY_ID = 'GET_MILEAGE_BY_ID',
}

export default QueryKeys;
