version: '3'
services:
  vtiger:
    image: javanile/vtiger-dev
    environment:
      - VT_SITE_URL=http://localhost:8080
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=vtiger
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - 8080:80
    volumes:
      - ./:/app
      - vtiger:/var/lib/vtiger
    links:
      - mysql

  mysql:
    image: mysql:5.5
    environment:
      - MYSQL_DATABASE=vtiger
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - mysql:/var/lib/mysql:rw

  nginx:
    image: nginx:1.16.1-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./localhost.cert:/etc/ssl/localhost.cert
      - ./localhost.key:/etc/ssl/localhost.key
    links:
      - vtiger
volumes:
  mysql:
  vtiger:
